import type { Application, Campaign, Creator } from './types';

export const demoCreators: Creator[] = [
  { id:'cr-1', profileId:'pr-1', name:'Vale López', username:'@valelopez', city:'Buenos Aires', category:'Moda', categories:['Moda','Belleza','Lifestyle'], followers:128000, engagement:6.3, startingPrice:80000, score:94, verified:true, bio:'Creo contenido auténtico sobre moda, belleza y vida cotidiana para comunidades que compran por recomendación.', initials:'VL', gradient:['#7c3aed','#ec4899'], portfolio:['Reel de lanzamiento','Historia con enlace','Contenido UGC'] },
  { id:'cr-2', profileId:'pr-2', name:'Santi Ríos', username:'@santirios', city:'Córdoba', category:'Fitness', categories:['Fitness','Deportes','Bienestar'], followers:95000, engagement:7.1, startingPrice:70000, score:92, verified:true, bio:'Entrenamiento, hábitos y reseñas honestas con foco en resultados y conversiones.', initials:'SR', gradient:['#2563eb','#06b6d4'], portfolio:['Rutina patrocinada','Review de producto','Evento deportivo'] },
  { id:'cr-3', profileId:'pr-3', name:'Mai Morales', username:'@maimorales', city:'Mendoza', category:'Viajes', categories:['Viajes','Lifestyle','Gastronomía'], followers:200000, engagement:5.8, startingPrice:120000, score:96, verified:true, bio:'Viajes, escapadas y experiencias premium contadas con estética editorial y métricas claras.', initials:'MM', gradient:['#f97316','#f43f5e'], portfolio:['Cobertura de hotel','Guía gastronómica','Reel de destino'] },
  { id:'cr-4', profileId:'pr-4', name:'Tomi Cáceres', username:'@tomicaceres', city:'Rosario', category:'Tecnología', categories:['Tecnología','Gaming','Apps'], followers:75000, engagement:6.2, startingPrice:80000, score:90, verified:true, bio:'Explico tecnología de manera simple y entretenida para audiencias jóvenes y emprendedoras.', initials:'TC', gradient:['#4f46e5','#8b5cf6'], portfolio:['Demo de app','Unboxing','Tutorial corto'] },
  { id:'cr-5', profileId:'pr-5', name:'Luz Herrera', username:'@luzherrera', city:'San Juan', category:'Gastronomía', categories:['Gastronomía','Familia','Eventos'], followers:42000, engagement:9.4, startingPrice:52000, score:91, verified:true, bio:'Recomendaciones locales, planes familiares y experiencias gastronómicas en Cuyo.', initials:'LH', gradient:['#ea580c','#eab308'], portfolio:['Visita al local','Menú destacado','Historia con reserva'] },
  { id:'cr-6', profileId:'pr-6', name:'Nico Paz', username:'@nicopaz', city:'Buenos Aires', category:'Humor', categories:['Humor','Entretenimiento','Lifestyle'], followers:310000, engagement:8.1, startingPrice:175000, score:95, verified:true, bio:'Humor cotidiano e integraciones naturales que generan conversación y recuerdo de marca.', initials:'NP', gradient:['#059669','#84cc16'], portfolio:['Sketch integrado','Challenge','Evento en vivo'] },
  { id:'cr-7', profileId:'pr-7', name:'Mica Suárez', username:'@micasuarez', city:'La Plata', category:'Belleza', categories:['Belleza','Moda','UGC'], followers:58000, engagement:10.2, startingPrice:60000, score:93, verified:true, bio:'Belleza real, tutoriales y contenido UGC listo para anuncios de alto rendimiento.', initials:'MS', gradient:['#be123c','#fb7185'], portfolio:['Tutorial','Antes y después','UGC para ads'] },
  { id:'cr-8', profileId:'pr-8', name:'Fran Luna', username:'@franluna', city:'San Juan', category:'Gaming', categories:['Gaming','Tecnología','Streaming'], followers:19000, engagement:12.1, startingPrice:39000, score:89, verified:false, bio:'Gaming, streaming y tecnología para una comunidad chica pero muy activa.', initials:'FL', gradient:['#0f766e','#3b82f6'], portfolio:['Gameplay','Streaming patrocinado','Review periférico'] }
];

export const demoCampaigns: Campaign[] = [
  { id:'ca-1', businessId:'bu-1', businessName:'Brasa Norte', title:'Noche parrillera', description:'Buscamos creadores locales para mostrar la experiencia completa del restaurante y generar reservas.', category:'Gastronomía', city:'San Juan', budgetMin:180000, budgetMax:260000, deliverables:['1 reel','3 historias','CTA a reservas'], deadline:'2026-07-01', status:'open', applicants:12, gradient:['#b45309','#ef4444'] },
  { id:'ca-2', businessId:'bu-2', businessName:'Marea', title:'Colección urbana', description:'Contenido UGC y reels para el lanzamiento de temporada, con derecho de uso por 60 días.', category:'Moda', city:'Mendoza', budgetMin:130000, budgetMax:210000, deliverables:['2 videos UGC','5 fotos'], deadline:'2026-07-10', status:'open', applicants:21, gradient:['#7c3aed','#ec4899'] },
  { id:'ca-3', businessId:'bu-3', businessName:'Punto App', title:'Lanzamiento de aplicación', description:'Creadores de tecnología y emprendimiento para explicar una app de forma simple y cercana.', category:'Tecnología', city:'Argentina', budgetMin:220000, budgetMax:350000, deliverables:['1 demo','1 reel','2 historias'], deadline:'2026-07-15', status:'open', applicants:8, gradient:['#1d4ed8','#06b6d4'] },
  { id:'ca-4', businessId:'bu-4', businessName:'Aura Club', title:'Experiencia wellness', description:'Jornada presencial con historias, un reel y reseña de experiencia.', category:'Fitness', city:'Córdoba', budgetMin:110000, budgetMax:170000, deliverables:['1 reel','4 historias'], deadline:'2026-06-28', status:'open', applicants:16, gradient:['#059669','#84cc16'] },
  { id:'ca-5', businessId:'bu-5', businessName:'Sur Hotel', title:'Escapada de invierno', description:'Cobertura de dos días para promocionar hospedaje y circuito gastronómico.', category:'Viajes', city:'Mendoza', budgetMin:150000, budgetMax:250000, deliverables:['2 reels','8 historias','10 fotos'], deadline:'2026-07-20', status:'open', applicants:27, gradient:['#0f766e','#3b82f6'] },
  { id:'ca-6', businessId:'bu-6', businessName:'Lúmina', title:'Rutina de cuidado', description:'Videos verticales auténticos orientados a conversión para redes y anuncios.', category:'Belleza', city:'Buenos Aires', budgetMin:160000, budgetMax:240000, deliverables:['3 videos UGC','uso en ads 90 días'], deadline:'2026-07-08', status:'open', applicants:19, gradient:['#be123c','#f97316'] }
];

export const demoApplications: Application[] = [
  { id:'ap-1', campaignId:'ca-1', campaignTitle:'Noche parrillera', creatorId:'cr-5', creatorName:'Luz Herrera', message:'Puedo realizar una cobertura familiar con foco en reservas.', proposedPrice:195000, status:'shortlisted', createdAt:'2026-06-10' },
  { id:'ap-2', campaignId:'ca-1', campaignTitle:'Noche parrillera', creatorId:'cr-8', creatorName:'Fran Luna', message:'Propongo contenido dinámico y una transmisión corta.', proposedPrice:180000, status:'pending', createdAt:'2026-06-11' },
  { id:'ap-3', campaignId:'ca-2', campaignTitle:'Colección urbana', creatorId:'cr-1', creatorName:'Vale López', message:'Tengo experiencia en lanzamientos de moda y UGC.', proposedPrice:205000, status:'accepted', createdAt:'2026-06-09' }
];
